# Copyright 2016 Susan Bennett, David Mitchell, Jim Nicholls
#
# This file is part of AutoHolds.
#
# AutoHolds is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# AutoHolds is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AutoHolds.  If not, see <http://www.gnu.org/licenses/>.
#
# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 05:13


from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_created_at', models.DateTimeField(auto_now_add=True)),
                ('log_updated_at', models.DateTimeField(auto_now=True)),
                ('log_notes', models.TextField(editable=False)),
                ('bib_record_number', models.IntegerField(editable=False)),
                ('bib_created_at', models.DateTimeField(editable=False)),
                ('author', models.CharField(blank=True, editable=False, max_length=255)),
                ('format', models.CharField(blank=True, editable=False, max_length=1)),
                ('language', models.CharField(blank=True, editable=False, max_length=3)),
                ('num_registrations_found', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HoldLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_created_at', models.DateTimeField(auto_now_add=True)),
                ('log_updated_at', models.DateTimeField(auto_now=True)),
                ('log_notes', models.TextField(editable=False)),
                ('patron_record_number', models.IntegerField(editable=False)),
                ('pickup_location', models.CharField(blank=True, editable=False, max_length=5)),
                ('successful', models.BooleanField(default=False, editable=False)),
                ('bib_log', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='holds_placed', to='staff.BibLog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_created_at', models.DateTimeField(auto_now_add=True)),
                ('log_updated_at', models.DateTimeField(auto_now=True)),
                ('log_notes', models.TextField(editable=False)),
                ('started_at', models.DateTimeField(editable=False)),
                ('ended_at', models.DateTimeField(editable=False, null=True)),
                ('successful', models.BooleanField(default=False, editable=False)),
                ('num_bibs_found', models.IntegerField(default=0, editable=False)),
                ('first_bib_record_number', models.IntegerField(editable=False, null=True)),
                ('first_bib_created_at', models.DateTimeField(editable=False, null=True)),
                ('last_bib_record_number', models.IntegerField(editable=False, null=True)),
                ('last_bib_created_at', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='biblog',
            name='run_log',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bibs_found', to='staff.RunLog'),
        ),
    ]
