# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_record_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patron_record_number', models.IntegerField(unique=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patron.Author')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patron.Format')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patron.Patron')),
            ],
        ),
        migrations.AddField(
            model_name='patron',
            name='authors',
            field=models.ManyToManyField(through='patron.Registration', to='patron.Author'),
        ),
        migrations.AddField(
            model_name='patron',
            name='pickup_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patron.PickupLocation'),
        ),
        migrations.AddField(
            model_name='author',
            name='patrons',
            field=models.ManyToManyField(through='patron.Registration', to='patron.Patron'),
        ),
    ]
