# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='code',
            field=models.CharField(default='-', max_length=1),
            preserve_default=False,
        ),
    ]
