# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0002_format_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='authority_record_number',
        ),
        migrations.AddField(
            model_name='author',
            name='friendly_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
