# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0003_auto_20160315_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuplocation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
