# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0005_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='patron.Language'),
            preserve_default=False,
        ),
    ]
