# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0006_registration_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patron.Format'),
        ),
    ]
