# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0007_auto_20160316_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='hold_queue_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
