# Copyright 2016 Susan Bennett, David Mitchell, Jim Nicholls
#
# This file is part of AutoHolds.
#
# AutoHolds is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# AutoHolds is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AutoHolds.  If not, see <http://www.gnu.org/licenses/>.
#
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 04:21

from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0008_registration_hold_queue_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='default_format',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='patron.Format'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patron',
            name='default_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='patron.Language'),
            preserve_default=False,
        ),
    ]
