# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0008_registration_hold_queue_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='default_format',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='patron.Format'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patron',
            name='default_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='patron.Language'),
            preserve_default=False,
        ),
    ]
