# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPropertyMyuser',
            fields=[
                ('code', models.TextField(max_length=3, primary_key=True, serialize=False)),
                ('display_order', models.IntegerField(unique=True)),
                ('is_public', models.BooleanField()),
                ('name', models.TextField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'sierra_view.material_property_myuser',
            },
        ),
    ]
