# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sierra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguagePropertyMyuser',
            fields=[
                ('code', models.TextField(max_length=3, primary_key=True, serialize=False)),
                ('display_order', models.IntegerField(unique=True)),
                ('is_public', models.BooleanField()),
                ('name', models.TextField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'language_property_myuser',
            },
        ),
        migrations.AlterModelTable(
            name='materialpropertymyuser',
            table='material_property_myuser',
        ),
    ]
