# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sierra', '0002_auto_20160316_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationMyuser',
            fields=[
                ('code', models.TextField(max_length=5, primary_key=True, serialize=False)),
                ('is_public', models.BooleanField()),
                ('name', models.TextField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'location_myuser',
            },
        ),
    ]
